name: Broken Link Checker

on: [deployment_status]

jobs:
  check_links:
    name: Check Links
    runs-on: ubuntu-latest
    if: github.event.deployment.environment == 'Netlify Preview' && github.event.deployment_status.state == 'success' && github.event.deployment.payload.context == 'branch-deploy'
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./website
        run: npm install
      - name: "[Action] Check Broken Links"
        uses: ./.github/actions/check_links
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          baseUrl: ${{ github.event.deployment.payload.environment_url }}
